### ISSUE TITLE
sorted bedGraph ouput

### ISSUE THREAD

**Issue by Shicheng-Guo** [dpryan79/PileOMeth#22]
In the present, the output of PileOMeth extract is non-sorted bedGraph output with the track header. Why not sort the bedgraph before put the header? I don't know whether it is harder to do?

**Comment by dpryan79** [comment]
The output should already be sorted according to the header of the BAM file. Can you give an example of it not being sorted?

**Comment by Shicheng-Guo** [comment]
It is interesting. I see maybe you are sorted the bedgraph with the header of the Bam file. However, usually, the sorted files is the following sorting. 

sort -k1,1 -k2,2 non-sorted.bedGraph > sorted.bedGraph

And we can see such kind of sorting is the requirement from bedgraph to bigwig. 

Obviously, if we run the bedGraphTobigwig with the output of the PileOMeth extract, the script will be reported error since:
1, PileOMeth ouputed bedGraph is 6 column not 4 column
2, PileOMeth outputed bedGraph is not sorted by: chr1, chr10, chr11,chr12....chr2, chr20, chr21,chr22, chr3, chrM, chrX, chrY. 
3, I think the order of PileOMeth extract bedgraph is chr1, chr2, chr3, ...chr22, chrM, chrX, chrY. 

I don't which order is more standardized. Maybe it is not the necessary to change it in PileOMeth extract. We can preapre a script to do the re-ordering easily.

**Comment by dpryan79** [comment]
That UCSC's tools complains when a file is already properly sorted is its problem. I will always output by however the BAM file is sorted, since this almost always matches how the fasta file is sorted as well.

If you want a 4 column bedGraph file then you can use the `--fraction` command. This is convenient for visualization, but not statistics, which is more the purpose of `PileOMeth`.
