### ISSUE TITLE
Third column in bedGraph is percentage?

### ISSUE THREAD

**Issue by kevinrue** [dpryan79/PileOMeth#7]
Dear Devon,
On Brent's advice, I have used PileOMeth on bwameth's BAM file.

In the output of the extract module, I see that the 4th column (chromosome counted as 1st column) contains values like "1000" or "666".
Given that the last two columns contain the methylated and unmethylated calls, it is obvious that the 4th column represents the ratio. I simply believe that you multiplied by 1000 instead of 100 to obtain the percentage.

Kind regards
Kevin

**Comment by dpryan79** [comment]
Hi Kevin,

Correct, that value is 1000 times the methylation percentage (then rounded to an integer). I multiplied by 1000 here simply to keep the formatting the same as what bismark uses (or at least used at some point, since I haven't checked recently).

This could easily be changed to be anything really. If we change it, it might be simplest to simply make it a floating point value [0.0-1.0]. We can also instead make it [0-100], I really have no particular preference.

I'll try to check again and see what bismark does, simply because I don't want to break any workflows that people have made expecting its formatting.

Best
Devon

**Comment by dpryan79** [comment]
I just checked and bismark either changed to [0-100] at some point or I just misremembered what it had been doing. In either case I'll change PileOMeth to also display this column as [0-100] and will also add a bit to the README to mention the exact format of the file.
